# レクチャーノート

## Todo
 - 例外処理
   - begin,rescue,end
   - retry
   - ensure
   - 数値チェックメソッドを作る
 - ブロック

## Lecture

### 例外処理

例外発生時に例外処理を行うための構文  

https://docs.ruby-lang.org/ja/latest/class/Exception.html

#### begin,rescue,end

beginスコープで例外が発生した場合はrescueでキャッチする  

format
```
begin
  # 処理
rescue
  # エラー処理
end
```

#### retry

retryは再度beginに処理を戻す  

format
```
begin
  # 処理
rescue
  retry # beginに戻る
end
```

#### ensure

ensureは終了処理を行う。（例外がおきた場合、おきない場合のどちらの場合も必ずとおる）  

format
```
begin
  # 処理
rescue
  # エラー処理
ensure
  # 終了処理
end
```

外部リソースは必ずensureでcloseすること
```
f = File.open('testfile')
begin
  # 処理
rescue
  # エラー処理
ensure
  f.close if f
end
```

#### 数値チェックメソッドを作る

rubyでは文字列をto_iで0として扱う 
```
"hoge".to_i
```

数値で処理を分ける場合は数値チェックメソッドを用意するとよい  
```
def isNumber?(str)
  begin
    Integer(str)
    true
  rescue
    false
  end
end
```

### 自作エラークラス

```
# 自作エラークラスを用意
class DBConnectionError < StandardError
  def message 
    "database connection failure... orz"
  end
end

# database接続メソッドの模倣
def database_connection
  error = true # 強制的にerrorにする
  raise DBConnectionError if error
  puts "database connection success!"
end

# 接続テスト
begin
  database_connection
rescue DBConnectionError => e
  puts e.message
end
```

### ブロック
ブロック = 引数と同様にブロックもメソッドに渡すこと可能  

```
def total(from,to)
  result = 0
  from.upto(to) do |num|
    if block_given? 
    # block
      result += yield(num)
    else 
    # no block
      result += num  
    end
  end
  result
end

p "total(1,5) => ",total(1,5)
p "total(1,5){|num| num * 2} => ",total(1,5){|num| num * 2}

```

## Reference
https://docs.ruby-lang.org/ja/2.4.0/doc/index.html

## Task
https://github.com/Tech-C2017/RubyStudy/blob/master/RubyQ6-20170624.md
